name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore src\AzureDevOpsDataCollector.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src\AzureDevOpsDataCollector.sln
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: AzureDevOpsDataCollector
        path: '**\bin\**\AzureDevOpsDataCollector.*'
