name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore src\AzureDevOpsDataCollector.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src\AzureDevOpsDataCollector.sln
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: AzureDevOpsDataCollector
        path: '**\bin\**\AzureDevOpsDataCollector.*'
    - name: Publish Nuget Package
      run: dotnet nuget push src\AzureDevOpsDataCollector.Console\bin\Release\AzureDevOpsDataCollector.Console.1.2.0.nupkg -k 4kjljljkl -s https://api.nuget.org/v3/index.json
